site_name: Mensor
nav:
  - Placeholder: index.md
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  palette:
    primary: light blue
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - mkdocs-jupyter